### PR TITLE
Added Arduino "ready to use" configuration files

### PR DESCRIPTION
**Pull request by Tungsteno74**
Hi,
this configuration has not been tested yet. I created initially because I needed for a project, but the project has changed before I had a chance to use it. I decided to put it here because so, in case I was needed again in the future, I'll know where to find it. Therefore, if anyone would like to test it with Arduino would be great.

Please, check if in the keywords.txt file all Datatypes, Functions/Methods and Constants are corrects.
thanks

### CODE REVIEW

**Comment by Tungsteno74** [comment]
Please, check if in the keywords.txt file all Datatypes, Functions/Methods and Constants are corrects.
thanks

**Comment by arkku** [comment]
I could consider adding any Arduino-specific configuration files to the main repository, but not copying existing files into an Arduino-specific directory hierarchy.

**Comment by Tungsteno74** [comment]
Thanks for your reply :)
I tried to find a way for make a config file that fit your specifications, but seems that arduino ide prior to 1.X need a directory hierarchy like this to work correctly (but i'm not an expert of arduino ide, so I could be wrong).

**Comment by arkku** [comment]
Even if Arduino needs the files in a specific directory, the hierarchy does not need to be replicated in the repository, i.e., there can be instructions for Arduino users to place the files from the root of the repository to a specific directory for use with Arduino.

Also, I am not changing the suffix of existing C files to Arduino's (frankly idiotic and unnecessary) `.ino`, but if Arduino requires an `.ino` file, one could be made to `#include` the necessary other files using the C pre-processor.

**Pull request closed without merging**
