### PR TITLE
make it compile with GCC

### PR DESCRIPTION
**Pull request by trutest**

### CODE REVIEW

**Comment by arkku** [comment]
In which context is this required? Specifying `-std=c99` (or later, or the GNU equivalent) should work with any GCC supporting C99 to begin with.

**Comment by trutest** [comment]
yes, you are correct about GCC. Sorry, I have a mixture of C++ and C files and didn't notice that it was compiling fine with GCC, just not G++. 
#ifdef __GNUG__ is equivalent to #if defined(__GNUC__) && defined(__cplusplus)

**Comment by arkku** [comment]
Hmm, but is it actually the case that `restrict` is never available if compiled with a C++ compiler? If so, the proper solution might be something like

```#ifdef __cplusplus
#ifdef __GNUG__
#define restrict __restrict__
#else
#define restrict
#endif
#endif
```

Or, what do you think? (My C++ knowledge is quite rusty.)

**Comment by trutest** [comment]
did you mean the following ? it looks fine to me.
```

#ifdef __GNUG__
#define restrict __restrict__
#else
#ifdef __cplusplus
#define restrict
#endif
#endif
```

**Comment by arkku** [comment]
I decided to just `#define restrict` when compiled as C++. IMO whole C++ option is largely clutter and I'm considering removing it entirely, as it should really be the responsibility of the C++ program to make the necessary preparations before the `#include` of a C header. (IIRC the current `#ifdef __cplusplus` was also a pull request.)

But as long as C++ is theoretically "supported", it is a valid concern that the `restrict` incompatibility should be solved, and c48895102d8a21df3a5fcf5c060182fba035302c seems like the minimal solution while allowing compiler-specific workarounds by defining it before the header is included.

**Pull request closed without merging**
